apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
    db: spleis # trengs bare ifm. 'spleis-db-policy'
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  filesFrom:
    - secret: google-sql-helse-spleis-spleis-spleis-opprydding-dev-fe3a79a6
      mountPath: /var/run/secrets/spleis_sql
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spleis-opprydding-dev-v1
    - name: KAFKA_RESET_POLICY
      value: LATEST
    - name: DATABASE_INSTANCE
      value: "helse-spleis"
  observability:
    logging:
      destinations:
        - id: elastic
