apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
    db: spleis # trengs bare ifm. 'spleis-db-policy'
  name: spleis-migrate
  namespace: tbd
spec:
  image: {{image}}
  parallelism: {{parallelism}}
  resources:
    limits:
      memory: 14336Mi
      cpu: 4000m
  kafka:
    pool: {{pool}}
  secureLogs:
    enabled: true
  envFrom:
    - secret: "{{avstemming-secret}}"
    - secret: "{{migrate-secret}}"
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  env:
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "{{database}}"
    - name: RUNTIME_OPTS
      value: "{{jobb}} {{arbeid_id}} {{ekstra_parametre}}"
    - name: DRYRUN
      value: "{{dryrun}}"
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
