apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
    db: spleis # trengs bare ifm. 'spleis-db-policy'
  name: spleis-avstemming
  namespace: tbd
spec:
  image: {{image}}
  schedule: "0 1 * * *"
  timeZone: Europe/Oslo
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-spleis-spleis-spleis-avstemming-c09f6283
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-prod-eacd
        role: roles/cloudsql.client
  env:
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "spleis2"
    - name: RUNTIME_OPTS
      value: "avstemming"
