apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  preStopHook:
    http:
      path: /stop
  replicas:
    min: 2
    max: 24
    scalingStrategy:
      kafka:
        topic: tbd.rapid.v1
        consumerGroup: tbd-spleis-v1
        threshold: 200
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 200m
      memory: 400Mi
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        diskAutoresize: true
        pointInTimeRecovery: true
        diskSize: 250
        diskType: SSD
        name: spleis2
        tier: db-custom-4-8960
        retainedBackups: 14
        databases:
          - name: spleis
            envVarPrefix: DATABASE
            users:
              - name: spleis-api
              - name: spleis-avstemming
              - name: spleis-migrate
        flags:
          - name: max_connections
            value: "350"
  secureLogs:
    enabled: true
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_EXTRA_TOPIC
    value: tbd.teknisk.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spleis-v1
  - name: KAFKA_RESET_POLICY
    value: NONE
  - name: TILKOMMEN_ARBEIDSGIVER
    value: "false"