name: Deploy alerts
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/alerts.yml'
      - 'deploy/prod-alertmanagerconfig.yml'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: deploy/prod-alertmanagerconfig.yml
