name: branch build

on:
  push:
    branches-ignore:
      - master

env:
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: test and build
        run: ./gradlew build
      - name: verifiser gyldig modell-jar
        run: unzip sykepenger-mediators/build/libs/sykepenger-model.jar -d /tmp/sykepenger-model
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          image_suffix: spleis
          tag: "${{ github.ref_name }}-${{ github.sha }}"
          dockerfile: Dockerfile
          docker_context: sykepenger-mediators
