name: Spleis

on:
  push:
    paths-ignore:
      - 'sykepenger-api/**'
      - 'sykepenger-opprydding-dev/**'
      - '.github/workflows/spleis-jobs.yml'
      - '.github/workflows/spleis-opprydding-dev.yml'
      - 'jobs/**'
      - 'doc/**'
      - '.idea/**'
      - 'README.md'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.github/workflows/alerts.yml'
      - 'deploy/prod-alertmanagerconfig.yml'
    branches:
      - master

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest-16-cores
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: test and build
        run: ./gradlew build -x :jobs:build -x :sykepenger-api:build -x :sykepenger-opprydding-dev:build
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
      - name: verifiser gyldig modell-jar
        run: unzip sykepenger-mediators/build/libs/sykepenger-model.jar -d /tmp/sykepenger-model
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          image_suffix: spleis
          dockerfile: Dockerfile
          docker_context: sykepenger-mediators
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml,deploy/db-dev.yml
          IMAGE: ${{ needs.build.outputs.image }}

  deployProd:
    name: deploy to prod
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: deploy/prod.yml,deploy/db-prod.yml
          IMAGE: ${{ needs.build.outputs.image }}
