name: Aiven config for de andre topicene våre

on:
  push:
    branches:
    - master
    paths:
    - 'deploy/aiven-teknisk-topic-dev.yml'
    - 'deploy/aiven-teknisk-topic-prod.yml'
    - 'deploy/aiven-subsumsjon-topic-dev'
    - 'deploy/aiven-subsumsjon-topic-prod'

jobs:
  deployDev:
    name: apply dev-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/aiven-teknisk-topic-dev.yml,deploy/aiven-subsumsjon-topic-dev

  deployProd:
    name: apply prod-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: deploy/aiven-teknisk-topic-prod.yml,deploy/aiven-subsumsjon-topic-prod
